pipeline {
    agent {
        dockerfile true
    }
    stages {
        stage('Test') {
            steps {
                sh 'mkdir -p reports'
                sh 'cd 002 && regula run -u  --include policy/s3_bucket_prefix.rego --format junit tf > output.xml'
            }
        }
    }
    post {
        always {
            junit 'reports/*.xml'
        }
    }
}