pipeline {
    agent {
        docker { 
            image 'fugue/regula:v0.8.0' 
            args '--entrypoint='
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'mkdir reports'
                sh 'cd 002 && regula run -u  --include policy/s3_bucket_prefix.rego --format junit tf > ../reports/output.xml'
            }
        }
    }
    post {
        always {
            junit 'reports/*.xml'
        }
    }
}